import { useState } from 'react';
import { filterIndicatorContracts } from '../calculations/indicators.ts';
import { INDICATOR_CONTRACTS } from '../data/indicatorsData.ts';
import type { AnalyticsFilters } from '../filters.ts';
import './indicators.css';
const fmt=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n);
const previousZones:Record<string,'Красная'|'Жёлтая'|'Зелёная'>={'contract-1':'Зелёная','contract-2':'Жёлтая','contract-3':'Зелёная','contract-4':'Жёлтая','contract-5':'Зелёная','contract-6':'Жёлтая'};
export const IndicatorsDashboard=({filters,onOpenContract}:{filters:AnalyticsFilters;onOpenContract:()=>void})=>{const[detail,setDetail]=useState('all');const rows=filterIndicatorContracts(INDICATOR_CONTRACTS,filters),amount=rows.reduce((s,x)=>s+x.amountMln,0),spent=rows.reduce((s,x)=>s+x.amountMln*x.financePercent/100,0),contractors=new Set(rows.map(x=>x.contractor)).size,transitions=rows.filter(x=>previousZones[x.id]!==x.oedkZone),details=detail==='red'?transitions:rows;const aggregate=(key:'subsidiary'|'service'|'kt777')=>Object.entries(rows.reduce<Record<string,{count:number;amount:number;spent:number}>>((r,x)=>{const k=x[key];r[k]||={count:0,amount:0,spent:0};r[k].count++;r[k].amount+=x.amountMln;r[k].spent+=x.amountMln*x.financePercent/100;return r},{})).sort((a,b)=>b[1].amount-a[1].amount).slice(0,12);if(!rows.length)return<section className="analytics-empty"><h2>По выбранным фильтрам нет договоров</h2></section>;return<div className="indicators-dashboard">
<section className="indicators-kpis"><article><span>Договоры</span><strong>{rows.length}</strong><small>доступная выборка</small></article><article><span>Общая стоимость</span><strong>{fmt(amount)}</strong><small>млн ₽</small></article><article><span>Подрядчики</span><strong>{contractors}</strong><small>уникальные ПО</small></article><article><span>Факт освоения</span><strong>{fmt(spent)}</strong><small>млн ₽</small></article><article><span>Средний ОЭДК</span><strong>{(rows.reduce((s,x)=>s+x.oedkScore,0)/rows.length).toFixed(1)}</strong><small>расчётное среднее</small></article><article><span>Смена зоны ОЭДК</span><strong>{transitions.length}</strong><small>к предыдущему периоду</small></article></section>
<section className="contracts-grid">{([['subsidiary','Распределение ПО и объёмов по ДО'],['service','Распределение по функциям'],['kt777','Распределение по услугам КТ‑777']]as const).map(([key,title])=><article className="indicator-card" key={key}><header><h2>{title}</h2><span>top‑12, остальные объединяются при большой выборке</span></header><div className="contract-bars">{aggregate(key).map(([label,v])=><button key={label} onClick={()=>setDetail('all')}><span>{label}</span><i><b style={{width:`${v.amount/Math.max(...aggregate(key).map(x=>x[1].amount))*100}%`}}/></i><strong>{fmt(v.amount)} млн ₽</strong><small>{v.count} дог.</small></button>)}</div></article>)}</section>
<section className="indicators-secondary"><article className="indicator-card"><header><h2>Факт освоения по функциям и услугам</h2><span>Сумма факта, без неизвестного физического плана</span></header><div className="contract-bars">{aggregate('service').map(([label,v])=><div key={label}><span>{label}</span><i><b style={{width:`${v.spent/Math.max(...aggregate('service').map(x=>x[1].spent))*100}%`}}/></i><strong>{fmt(v.spent)} млн ₽</strong></div>)}</div></article><article className="indicator-card"><header><h2>Факт освоения по ДО</h2></header><div className="contract-bars">{aggregate('subsidiary').map(([label,v])=><div key={label}><span>{label}</span><i><b style={{width:`${v.spent/Math.max(...aggregate('subsidiary').map(x=>x[1].spent))*100}%`}}/></i><strong>{fmt(v.spent)} млн ₽</strong></div>)}</div></article></section>
<section className="indicators-main"><article className="indicator-card"><header><h2>Запланированная и выплаченная мотивация по ПО</h2><span>Сравнение настроено только для этого графика</span></header><div className="motivation-chart">{rows.map(x=><div key={x.id}><span>{x.contractor}</span><i><b style={{width:`${Math.min(100,x.motivationMln*1.25/12*100)}%`}}/><em style={{width:`${Math.min(100,x.motivationMln/12*100)}%`}}/></i><strong>{x.motivationMln} млн ₽</strong></div>)}</div></article><aside className="indicator-attention"><header><h2>В фокусе: переходы ОЭДК</h2><span>Из одной зоны в другую</span></header>{transitions.map(x=><button key={x.id} onClick={()=>setDetail('red')}><strong>{x.contractor}</strong><span>{previousZones[x.id]} → {x.oedkZone}</span><small>{x.number} · {x.oedkScore} баллов</small></button>)}</aside></section>
<section className="segment-details"><header><div><h2>Договоры, из которых складывается статистика</h2><span>Первые 5 из {details.length}; агрегация не рендерит тысячи DOM‑элементов</span></div></header><div>{details.slice(0,5).map(x=><article key={x.id}><strong>{x.number}</strong><span>{x.contractor}</span><small>{x.service} · {x.kt777} · {fmt(x.amountMln)} млн ₽</small><button onClick={onOpenContract}>Открыть договор</button></article>)}</div></section></div>};
