import { countMeasuresByStatus, countMeasuresLinkedToBreach, countMeasuresWithoutResponsible, countUniqueMeasures, filterMeasures } from '../calculations/metrics.ts';
import { DEMO_MEASURE_BREACH_LINKS, DEMO_MEASURES } from '../data/demoMeasures.ts';
import type { AnalyticsFilters } from '../filters.ts';
import './pcm.css';

const subsidiaryByContractor: Record<string,string>={'Альфа-Строй':'ГПН-Ямал','БетаГрупп':'ГПН-Ямал','Гамма-ТЭК':'Мессояханефтегаз','Дельта Инж':'Мессояханефтегаз','Сигма Плюс':'Газпромнефть-Хантос','Омега-Сервис':'Газпромнефть-Хантос'};
const serviceGroup=(service:string)=>service.includes('Бурение')||service.includes('скважин')?'Бурение':service.includes('обустрой')?'Обустройство':'ТКРС';
export const PcmDashboard=({filters}:{filters:AnalyticsFilters})=>{const allContractors=[...new Set(DEMO_MEASURES.map(x=>x.contractor))],allServices=[...new Set(DEMO_MEASURES.map(x=>x.service))];const base=filterMeasures(DEMO_MEASURES,{contractors:filters.contractor==='all'?allContractors:[filters.contractor],services:allServices,monthFrom:0,monthTo:7});const rows=base.filter(x=>(filters.subsidiary==='all'||subsidiaryByContractor[x.contractor]===filters.subsidiary)&&(filters.service==='all'||serviceGroup(x.service)===filters.service));const status=countMeasuresByStatus(rows),total=countUniqueMeasures(rows),without=countMeasuresWithoutResponsible(rows),linked=countMeasuresLinkedToBreach(rows,DEMO_MEASURE_BREACH_LINKS);const contractors=[...new Set(rows.map(x=>x.contractor))];if(!rows.length)return<section className="analytics-empty"><h2>По выбранным фильтрам нет мероприятий</h2><p>Измените ДО, услугу или подрядчика.</p></section>;return<div className="pcm-dashboard">
<section className="pcm-kpis"><article><span>Всего мероприятий</span><strong>{total}</strong><small>уникальные contract_measure.id</small></article><article><span>Новые</span><strong>{status['Новый']||0}</strong><small>прямой статус</small></article><article><span>В работе</span><strong>{status['В работе']||0}</strong><small>прямой статус</small></article><article><span>Реализовано</span><strong>{status['Реализовано']||0}</strong><small>прямой статус</small></article><article><span>Без ответственного</span><strong>{without}</strong><small>пустое responsible_person</small></article><article><span>Связаны с нарушением</span><strong>{linked}</strong><small>физическая связь</small></article></section>
<section className="pcm-main"><article className="pcm-card"><header><h2>В каких статусах находятся мероприятия?</h2><span>Количество уникальных мероприятий по status_code</span></header><div className="pcm-status">{contractors.map(c=>{const items=rows.filter(x=>x.contractor===c),s=countMeasuresByStatus(items);return<div key={c}><span>{c}</span><i><b className="pcm-new" style={{flex:s['Новый']||0}}/><b className="pcm-work" style={{flex:s['В работе']||0}}/><b className="pcm-done" style={{flex:s['Реализовано']||0}}/></i><strong>{items.length}</strong></div>})}</div><footer><span><i className="pcm-new"/>Новый</span><span><i className="pcm-work"/>В работе</span><span><i className="pcm-done"/>Реализовано</span></footer></article><aside className="pcm-attention"><header><h2>Требует внимания</h2><span>Только отсутствие прямого ответственного</span></header>{contractors.map(c=>({c,count:countMeasuresWithoutResponsible(rows.filter(x=>x.contractor===c))})).filter(x=>x.count).slice(0,5).map(x=><article key={x.c}><strong>{x.c}</strong><span>Без ответственного: {x.count}</span><small>Не является показателем просрочки</small></article>)}</aside></section>
<section className="pcm-secondary"><article className="pcm-card"><header><h2>Как меняется количество созданных мероприятий?</h2><span>По месяцу создания записи</span></header><div className="pcm-months">{['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг'].map((m,i)=>{const count=rows.filter(x=>x.monthIndex===i).length;return<div key={m}><i style={{height:`${Math.max(8,count/Math.max(...[0,1,2,3,4,5,6,7].map(k=>rows.filter(x=>x.monthIndex===k).length))*100)}%`}}/><b>{count}</b><span>{m}</span></div>})}</div></article><article className="pcm-card"><header><h2>Сколько мероприятий связано с нарушениями?</h2><span>По lnk_contract_measure_breach</span></header><div className="pcm-links"><strong>{linked}</strong><span>связаны</span><strong>{total-linked}</strong><span>без связи</span></div></article></section>
<section className="pcm-note"><strong>Не рассчитывается:</strong> просрочка, выполнение в срок и эффективность ПКМ — в contract_measure нет подтверждённых контрольной и фактической дат завершения.</section></div>};
