import { useState } from 'react';
import { filterRatings, summarizeRating } from '../calculations/rating.ts';
import { RATING_RECORDS } from '../data/ratingData.ts';
import type { AnalyticsFilters } from '../filters.ts';
import './rating.css';

export const RatingDashboard = ({ filters }: { filters: AnalyticsFilters }) => {
  const [dimension, setDimension] = useState<'brigade'|'subsidiary'|'contractor'>('brigade');
  const records = filterRatings(RATING_RECORDS, filters);
  const summary = summarizeRating(records);
  const periods = [...new Set(records.map(item => item.period))];
  const latest = records.filter(item => item.period === periods[periods.length - 1]);
  const groups = Object.entries(latest.reduce<Record<string, number[]>>((result, item) => { const key = item[dimension]; (result[key] ||= []).push(item.score); return result; }, {})).map(([label, scores]) => ({ label, score: scores.reduce((a,b)=>a+b,0)/scores.length }));
  if (!records.length) return <section className="analytics-empty"><h2>По выбранным фильтрам нет рейтингов</h2><p>Измените ДО, услугу или подрядчика.</p></section>;
  return <div className="rating-dashboard">
    <section className="rating-kpis"><article><span>Средний переданный балл</span><strong>{summary.average.toFixed(1)}</strong><small>расчётное среднее</small></article><article><span>Зоны: зелёная / жёлтая / красная</span><strong>{summary.zones.green} / {summary.zones.yellow} / {summary.zones.red}</strong><small>по переданному цвету</small></article><article><span>Перешли в худшую зону</span><strong>{summary.worse}</strong><small>к предыдущему периоду</small></article><article><span>Перешли в лучшую зону</span><strong>{summary.better}</strong><small>к предыдущему периоду</small></article><article><span>Со стоп-фактором</span><strong>{summary.stopFactors}</strong><small>прямой признак</small></article><article><span>Предварительные</span><strong>{summary.preliminary}</strong><small>не смешиваются с подтверждёнными</small></article></section>
    <section className="rating-main"><article className="rating-card"><header><h2>Как меняется переданный итоговый балл?</h2><span>ЛК не пересчитывает итоговый рейтинг</span></header><div className="rating-lines">{[...new Set(records.map(item=>item.brigade))].map(brigade => <div key={brigade}><strong>{brigade}</strong>{periods.map(period => { const item=records.find(row=>row.brigade===brigade&&row.period===period); return <i key={period} title={`${period}: ${item?.score}`} className={`rating-dot rating-dot--${item?.zone.toLowerCase()}`} style={{ height: `${item?.score || 0}%` }}><b>{item?.score}</b><small>{period}</small></i>})}</div>)}</div></article><aside className="rating-attention"><header><h2>Проблемные зоны</h2><span>Цвет, балл и стоп-фактор из источника</span></header>{latest.filter(item=>item.zone!=='Зелёная'||item.stopFactor).map(item=><article key={item.brigade}><strong>{item.brigade}</strong><span>{item.score} баллов · {item.zone.toLowerCase()} зона</span><small>{item.contractor}{item.stopFactor?' · стоп-фактор':''}</small></article>)}</aside></section>
    <section className="rating-secondary"><article className="rating-card"><header><h2>Как меняется распределение по зонам?</h2></header><div className="rating-zones">{periods.map(period=>{const rows=records.filter(item=>item.period===period); return <div key={period}><span>{period}</span><i><b className="rz-red" style={{flex:rows.filter(x=>x.zone==='Красная').length}}/><b className="rz-yellow" style={{flex:rows.filter(x=>x.zone==='Жёлтая').length}}/><b className="rz-green" style={{flex:rows.filter(x=>x.zone==='Зелёная').length}}/></i></div>})}</div></article><article className="rating-card"><header><h2>Как различаются результаты?</h2><nav><button onClick={()=>setDimension('brigade')}>Бригады</button><button onClick={()=>setDimension('subsidiary')}>ДО</button><button onClick={()=>setDimension('contractor')}>Подрядчики</button></nav></header><div className="rating-compare">{groups.map(group=><div key={group.label}><span>{group.label}</span><i><b style={{width:`${group.score}%`}}/></i><strong>{group.score.toFixed(1)}</strong></div>)}</div></article></section>
  </div>;
};
