import { useState } from 'react';
import './reports.css';
type Status='idle'|'forming'|'ready';
const reports=[
{id:'REPORT-IDP',title:'Индикативные показатели',description:'Договорные, финансовые и операционные показатели.',period:'Ежеквартально',version:'Форма 2026.1',confirmed:true,warning:'Частичные данные FORM-IDP'},
{id:'REPORT-DPR',title:'Допретензионная работа',description:'Случаи, этапы, суммы и сроки ДПР.',period:'Ежеквартально',version:'Форма 2026.2',confirmed:true,warning:'Обновление задержано'},
{id:'REPORT-ADDENDUMS',title:'Реестр дополнительных соглашений',description:'Условия, этапы, сроки и результаты заключения ДС.',period:'Ежемесячно',version:'Реестр ДС 2026.1',confirmed:true,warning:'Обновление задержано'},
{id:'REPORT-SAFETY',title:'Нарушения ВА/ВК по бурению и ТКРС',description:'Стандартный отчёт по нарушениям и тяжести.',period:'По запросу',version:'Шаблон ожидается',confirmed:false,warning:'Точный состав колонок не передан'},
{id:'REPORT-PCM',title:'Общий отчёт по ПКМ ВА/ВК',description:'Мероприятия, статусы и связи с нарушениями.',period:'По запросу',version:'Шаблон ожидается',confirmed:false,warning:'Точный состав колонок не передан'},
] as const;
export const ReportsDashboard=()=>{const[query,setQuery]=useState('');const[statuses,setStatuses]=useState<Record<string,Status>>({});const visible=reports.filter(r=>r.title.toLowerCase().includes(query.toLowerCase()));const generate=(id:string)=>{setStatuses(s=>({...s,[id]:'forming'}));window.setTimeout(()=>setStatuses(s=>({...s,[id]:'ready'})),1200)};return<div className="reports-dashboard"><section className="reports-tools"><label>Поиск отчёта<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название или назначение"/></label><div><strong>{visible.length}</strong><span>форм в каталоге</span></div></section><section className="reports-grid">{visible.map(report=>{const status=statuses[report.id]||'idle';return<article key={report.id} className={!report.confirmed?'report-card report-card--disabled':'report-card'}><header><span>{report.id}</span><b>{report.confirmed?(report.warning?'Есть предупреждения':'Готов'):'Недостаточно данных'}</b></header><h2>{report.title}</h2><p>{report.description}</p><dl><div><dt>Периодичность</dt><dd>{report.period}</dd></div><div><dt>Версия</dt><dd>{report.version}</dd></div><div><dt>Актуальность</dt><dd>29.08.2026, 18:10</dd></div></dl><aside>{report.warning}</aside>{report.confirmed?<button disabled={status==='forming'} onClick={()=>generate(report.id)}>{status==='forming'?'Формируется…':status==='ready'?'Скачать XLSX':'Сформировать'}</button>:<button disabled>Нужен шаблон</button>}</article>})}</section><section className="reports-note"><strong>Матрица взаимодействия УИД</strong><span>Доступна только в разделе команды договора и не включена в общую аналитику.</span></section></div>};
